{{- $webapp := .Values.georchestra.webapps.metadata_editor -}}
{{- if $webapp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-metadata-editor-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-metadata-editor
  {{- with $webapp.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-metadata-editor
{{- end }}
